


# Technical
WIDTH = 1280
HEIGHT = 720
WINDOW_TITLE = 'fall\'s Epic Platformer'

# Map
TILE_SIZE = 128


# Player
PLAYER_SPEED = 10
PLAYER_JUMP = 25
RANGED_ATTACK_SPEED = 50
RANGED_ATTACK_DAMAGE = 5
PLAYER_IMMUNITY_TIME = 1 # In seconds

# Enemy
ENEMY_HEALTH = 20
ENEMY_SPEED = 5
ENEMY_JUMP = 15
ENEMY_PROVOKE_DIST = 250
ENEMY_ATTEMPT_JUMP_DIST = 400
ENEMY_LOSE_PROVOKE_DIST = 1500
ENEMY_IMMUNITY_TIME = 0.2 # In seconds

# World
GRAVITY = 1